# -*- coding: utf-8 -*-

$LOAD_PATH.unshift('/Library/RubyMotion/lib')

require 'motion/project'
require 'rubygems'
require 'bubble-wrap'

Motion::Project::App.setup do |app|
  app.name = ''  
  app.delegate_class = ''  
  app.files.unshift(File.join(Gem.bin_path('dynamics', 'dynamics').gsub(File.join('bin', 'dynamics'), ''), 'lib', 'dynamics.rb')) 
end