# -*- coding: utf-8 -*-

$LOAD_PATH.unshift('/Library/RubyMotion/lib')

require 'motion/project'
require 'rubygems'
require 'bubble-wrap'
require 'dynamics'

Motion::Project::App.setup do |app|
  app.name = ''  
  app.delegate_class = ''  
  app.icons = %w{icon.png}
    
  Dynamics::setup_framework(app, File.dirname(__FILE__))
end

